[2025-08-28T18:40:13.389+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-28T18:40:13.401+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training scheduled__2025-08-27T03:00:00+00:00 [queued]>
[2025-08-28T18:40:13.405+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training scheduled__2025-08-27T03:00:00+00:00 [queued]>
[2025-08-28T18:40:13.405+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-28T18:40:13.410+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_training> on 2025-08-27 03:00:00+00:00
[2025-08-28T18:40:13.413+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=136) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-28T18:40:13.414+0000] {standard_task_runner.py:72} INFO - Started process 137 to run task
[2025-08-28T18:40:13.414+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'execute_training', 'scheduled__2025-08-27T03:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmpz39dq_5b']
[2025-08-28T18:40:13.415+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask execute_training
[2025-08-28T18:40:13.437+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.execute_training scheduled__2025-08-27T03:00:00+00:00 [running]> on host fbfd4480322c
[2025-08-28T18:40:13.468+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='datamasterylab.com' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='execute_training' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-27T03:00:00+00:00'
[2025-08-28T18:40:13.468+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-28T18:40:14.210+0000] {font_manager.py:1639} INFO - generated new fontManager
[2025-08-28T18:40:16.845+0000] {warnings.py:112} WARNING - /opt/***/dags/fraud_detection_training.py:45: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  from numpy.array_api import astype

[2025-08-28T18:40:16.888+0000] {fraud_detection_training_dag.py:23} INFO - Initializing fraud detection training
[2025-08-28T18:40:16.892+0000] {fraud_detection_training.py:120} INFO - Configuration loaded successfully
[2025-08-28T18:40:17.231+0000] {fraud_detection_training.py:163} INFO - Minio connection verified. Buckets: ['mlflow']
[2025-08-28T18:40:17.841+0000] {logging_mixin.py:190} WARNING - 2025/08/28 18:40:17 INFO mlflow.tracking.fluent: Experiment with name 'fraud_detection' does not exist. Creating a new experiment.
[2025-08-28T18:40:17.937+0000] {fraud_detection_training.py:292} INFO - Starting model training process
[2025-08-28T18:40:17.937+0000] {fraud_detection_training.py:188} INFO - Connecting to kafka topic transactions
[2025-08-28T18:40:17.938+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-08-28T18:40:17.942+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.6', 9092)]>: Broker version identified as 2.6
[2025-08-28T18:40:17.942+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Connection complete.
[2025-08-28T18:40:17.943+0000] {consumer.py:120} WARNING - group_id is None: disabling auto-commit.
[2025-08-28T18:40:17.943+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('transactions',)
[2025-08-28T18:40:17.947+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('transactions', 0)]
[2025-08-28T18:40:17.948+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.6', 9092)]>: connecting to kafka:9092 [('172.18.0.6', 9092) IPv4]
[2025-08-28T18:40:17.948+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Connection complete.
[2025-08-28T18:40:17.948+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. 
[2025-08-28T18:40:17.950+0000] {fetcher.py:418} INFO - Resetting offset for partition ('transactions', 0) to offset 0.
[2025-08-28T18:41:51.254+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>: Closing connection. 
[2025-08-28T18:41:51.261+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.6', 9092)]>
[2025-08-28T18:41:53.456+0000] {fraud_detection_training.py:213} INFO - Kafka data read successfully with fraud rate: 0.36%
[2025-08-28T18:41:58.681+0000] {fraud_detection_training.py:372} INFO - Starting hyperparameter tuning...
[2025-08-28T18:41:58.686+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-08-28T18:42:10.257+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9. For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2025-08-28T18:42:10.288+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-28T18:42:10.289+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-08-28T18:57:55.023+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-28T18:57:55.033+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training scheduled__2025-08-27T03:00:00+00:00 [queued]>
[2025-08-28T18:57:55.036+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training scheduled__2025-08-27T03:00:00+00:00 [queued]>
[2025-08-28T18:57:55.037+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-28T18:57:55.042+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_training> on 2025-08-27 03:00:00+00:00
[2025-08-28T18:57:55.045+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-28T18:57:55.045+0000] {standard_task_runner.py:72} INFO - Started process 89 to run task
[2025-08-28T18:57:55.046+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'execute_training', 'scheduled__2025-08-27T03:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmptkadp29i']
[2025-08-28T18:57:55.046+0000] {standard_task_runner.py:105} INFO - Job 15: Subtask execute_training
[2025-08-28T18:57:55.066+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.execute_training scheduled__2025-08-27T03:00:00+00:00 [running]> on host d31ca6a4308c
[2025-08-28T18:57:55.118+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='nguyentientai223.com' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='execute_training' AIRFLOW_CTX_EXECUTION_DATE='2025-08-27T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-27T03:00:00+00:00'
[2025-08-28T18:57:55.119+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-28T18:57:55.859+0000] {font_manager.py:1639} INFO - generated new fontManager
[2025-08-28T18:57:58.437+0000] {warnings.py:112} WARNING - /opt/***/dags/fraud_detection_training.py:45: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  from numpy.array_api import astype

[2025-08-28T18:57:58.475+0000] {fraud_detection_training_dag.py:23} INFO - Initializing fraud detection training
[2025-08-28T18:57:58.479+0000] {fraud_detection_training.py:120} INFO - Configuration loaded successfully
[2025-08-28T18:57:58.806+0000] {fraud_detection_training.py:163} INFO - Minio connection verified. Buckets: ['mlflow']
[2025-08-28T18:57:59.576+0000] {fraud_detection_training.py:292} INFO - Starting model training process
[2025-08-28T18:57:59.576+0000] {fraud_detection_training.py:188} INFO - Connecting to kafka topic transactions
[2025-08-28T18:57:59.578+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.2', 9092)]>: connecting to kafka:9092 [('172.18.0.2', 9092) IPv4]
[2025-08-28T18:57:59.593+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.2', 9092)]>: Broker version identified as 2.6
[2025-08-28T18:57:59.593+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.2', 9092)]>: Connection complete.
[2025-08-28T18:57:59.595+0000] {consumer.py:120} WARNING - group_id is None: disabling auto-commit.
[2025-08-28T18:57:59.595+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('transactions',)
[2025-08-28T18:57:59.598+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('transactions', 0)]
[2025-08-28T18:57:59.599+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.2', 9092)]>: connecting to kafka:9092 [('172.18.0.2', 9092) IPv4]
[2025-08-28T18:57:59.600+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.2', 9092)]>: Connection complete.
[2025-08-28T18:57:59.601+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.2', 9092)]>: Closing connection. 
[2025-08-28T18:57:59.703+0000] {fetcher.py:418} INFO - Resetting offset for partition ('transactions', 0) to offset 0.
[2025-08-28T18:58:23.691+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.2', 9092)]>: Closing connection. 
[2025-08-28T18:58:23.693+0000] {fetcher.py:786} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.2.15, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.2', 9092)]>
[2025-08-28T18:58:24.609+0000] {fraud_detection_training.py:213} INFO - Kafka data read successfully with fraud rate: 0.35%
[2025-08-28T18:58:28.864+0000] {fraud_detection_training.py:372} INFO - Starting hyperparameter tuning...
[2025-08-28T18:58:28.868+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-08-28T18:59:08.455+0000] {fraud_detection_training.py:376} INFO - Best hyperparameters: {'classifier__subsample': 0.6, 'classifier__reg_alpha': 0, 'classifier__max_depth': 7, 'classifier__learning_rate': 0.1, 'classifier__gamma': 0, 'classifier__colsample_bytree': 0.6}
[2025-08-28T18:59:08.789+0000] {fraud_detection_training.py:384} INFO - Optimal threshold determined: 0.7700
[2025-08-28T18:59:10.118+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-08-28T18:59:10.749+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/mlflow/types/utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(

[2025-08-28T18:59:10.761+0000] {logging_mixin.py:190} WARNING - 2025/08/28 18:59:10 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
[2025-08-28T18:59:15.196+0000] {logging_mixin.py:190} WARNING - Successfully registered model 'fraud_detection_model'.
[2025-08-28T18:59:15.273+0000] {logging_mixin.py:190} WARNING - 2025/08/28 18:59:15 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: fraud_detection_model, version 1
[2025-08-28T18:59:15.274+0000] {logging_mixin.py:190} WARNING - Created version '1' of model 'fraud_detection_model'.
[2025-08-28T18:59:15.382+0000] {fraud_detection_training.py:448} INFO - Training successfully completed with metrics: {'auc_pr': 0.48834898509183183, 'precision': 0.8181818181818182, 'recall': 0.46551724137931033, 'f1': 0.5934065934065934, 'threshold': 0.7700138092041016}
[2025-08-28T18:59:15.392+0000] {logging_mixin.py:190} INFO - 🏃 View run shivering-panda-720 at: http://mlflow-server:5500/#/experiments/1/runs/fa3ee90a9d9640d4af64a3574e7c444f
[2025-08-28T18:59:15.392+0000] {logging_mixin.py:190} INFO - 🧪 View experiment at: http://mlflow-server:5500/#/experiments/1
[2025-08-28T18:59:15.487+0000] {python.py:240} INFO - Done. Returned value was: {'status': 'success', 'precision': {'auc_pr': 0.48834898509183183, 'precision': 0.8181818181818182, 'recall': 0.46551724137931033, 'f1': 0.5934065934065934, 'threshold': 0.7700138092041016}}
[2025-08-28T18:59:15.509+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-28T18:59:15.510+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fraud_detection_training, task_id=execute_training, run_id=scheduled__2025-08-27T03:00:00+00:00, execution_date=20250827T030000, start_date=20250828T185755, end_date=20250828T185915
[2025-08-28T18:59:15.561+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-28T18:59:15.585+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-28T18:59:15.586+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
